--- #YAML:1.0
name:               Win32-IPHelper
version:            0.08
abstract:           Perl wrapper for Win32 IP Helper functions and structures.
author:
    - Luigino Masarati <lmasarati@hotmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    enum:        0
    Win32::API:  0.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
