--- #YAML:1.0
name:                Win32-IPHelper
version:             0.06
abstract:            Perl wrapper for Win32 IP Helper functions and structures.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Win32::API:                    0.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Luigino Masarati <lmasarati@hotmail.com>
