---
abstract: 'Perl wrapper for Win32 IP Helper functions and structures.'
author:
  - 'Luigino Masarati <lmasarati@hotmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-IPHelper
no_index:
  directory:
    - t
    - inc
requires:
  Win32::API: 0.2
version: 0.07
