# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-IPHelper
version:      0.05
version_from: IPHelper.pm
installdirs:  site
requires:
    Win32::API:                    0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
